version: "2"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - ${HTTP_PORT}:80
      - ${ADMIN_PORT}:81
      - ${HTTPS_PORT}:443
    networks:
      - nginxproxymanager
    volumes:
      - app_data:/data
      - letsencrypt:/etc/letsencrypt
      - ./production.json:/app/config/production.json
    restart: unless-stopped

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "npm"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nginxproxymanager
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

networks:
  nginxproxymanager:
    driver: overlay
    attachable: true

volumes:
    app_data:
    db_data:
    letsencrypt:
